# -*- coding: utf-8 -*-
"""VDS Report.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdX599NKgriS-E4tZZ6FlZkaUAhSwS4h

# Download and check VDS data published by TravelMidwest.com
"""

# Commented out IPython magic to ensure Python compatibility.
#!pip install pandas-read-xml
# %cd '/content/drive/Shareddrives/GTIS/XML Publication Checks/VDS Report'

"""## Download VDSReport.xml.gz and save into pandas DataFrame object 'df'"""

import requests
from requests.auth import HTTPBasicAuth
import gzip 
from io import BytesIO
import pandas as pd
import pandas_read_xml as pdx
from pandas_read_xml import flatten, auto_flatten, fully_flatten, auto_separate_tables
import time
from datetime import datetime, timezone
import xml.dom.minidom

# Provide username and password for TravelMidwest.com account
username = 'XXX'
password = 'XXX'
url = 'https://www.travelmidwest.com/lmiga/VDSReport.xml.gz'
package = 'com.gcmtravel.VDSReport'

def columnNameMapper(columnName: str) -> str:
  """This function renames the DataFrame columns to make them look a little nicer.

  Parameters
  ----------
  columnName - name of column as passed in from the pandas rename() method

  Returns
  -------
  str - new name for the column
  """
  if columnName.find(package+'Element|parent|location|locationElement|') == 0:
    return columnName[len(package+'Element|parent|location|locationElement|'):]
  elif columnName.find(package+'Element|parent|') == 0:
    return columnName[len(package+'Element|parent|'):]
  elif columnName.find(package+'Element|') == 0:
    return columnName[len(package+'Element|'):]
  return columnName

with requests.get(url, auth=HTTPBasicAuth(username, password), stream=True) as r:
  xmlstr = gzip.decompress(data=r.content).decode('utf-8')
  with open('VDSReport.xml', 'w') as out:
    dom = xml.dom.minidom.parseString(xmlstr)
    out.write(dom.toprettyxml(indent='  '))
  df = pdx.read_xml(xmlstr, [ package ]).pipe(fully_flatten).rename(columns=columnNameMapper).set_index('fieldDeviceID')
  df['speed'] = df['speed'].astype(float)
  df['speedMph'] = df['speed'] * 2.23694
  df['latLongPointLoc|coord|latitude'] = df['latLongPointLoc|coord|latitude'].astype(float) / 100000.0
  df['latLongPointLoc|coord|longitude'] = df['latLongPointLoc|coord|longitude'].astype(float) / 100000.0
  df['timestamp'] = df['lastUpdateTime'].astype(float).apply(func=lambda t: datetime.fromtimestamp(t/1000., tz=None))
  df['age'] = datetime.utcnow() - df['timestamp']
  # some VDS are missing fieldDeviceID values!   Drop those rows because they cause an error in source_data = line below
  df = df[~df.index.isna()]
  # fully_flatten will cause fieldDeviceID duplications when a VDS has more than one location profile, let's merge these together
  df = df.groupby(level=0).first()
  #df['timestamp'] = df['lastUpdateTime'].astype(float).apply(lambda t : pd.to_datetime(t))

report_dicts = []
for idprefix in ['IL-TESTTSC', 'IL-IDOTD2', 'MN-IRIS']:
  source_data = df[df.index.str.contains(idprefix)]
  invalid = source_data[(source_data['speed']  <= 0) | source_data['speed'].isna() | (source_data['age'] > '15 minutes') | (source_data['deviceStatus'] != 'OPERATIONAL') | (source_data['dataStatus'] == 'FIELD_DATA_INFEASIBLE_FOUND_AUTO')]
  failed_validation = source_data[(source_data['dataStatus'] == 'FIELD_DATA_INFEASIBLE_FOUND_AUTO')]
  unresolved = source_data[~source_data['locStatus'].str.contains('LOCATION_RESOLVED')]
  valid = source_data[~((source_data['speed']  <= 0) | source_data['speed'].isna() | (source_data['age'] > '15 minutes') | (source_data['deviceStatus'] != 'OPERATIONAL') | (source_data['dataStatus'] == 'FIELD_DATA_INFEASIBLE_FOUND_AUTO'))]
  valid_unresolved = valid[~valid['locStatus'].str.contains('LOCATION_RESOLVED')]
  missing_speed = source_data[source_data['speed']  <= 0 | source_data['speed'].isna()]
  old = source_data[(source_data['age'] > '15 minutes')]
  non_operational = source_data[(source_data['deviceStatus'] != 'OPERATIONAL')]
  report_dicts.append({'source': idprefix, 
                       'invalid': invalid.shape[0], 
                       'failed_validation': failed_validation.shape[0], 
                       'unresolved': unresolved.shape[0],
                       'valid': valid.shape[0],
                       'valid_unresolved': valid_unresolved.shape[0],
                       'missing_speed': missing_speed.shape[0],
                       'old': old.shape[0],
                       'non_operational': non_operational.shape[0],
                       'total': source_data.shape[0],
                       })
  with pd.ExcelWriter('VDS-'+idprefix+'.xlsx') as writer:
    source_data.to_excel(writer, sheet_name=idprefix, freeze_panes=(1,1))
    valid.to_excel(writer, sheet_name='Valid', freeze_panes=(1,1))
    invalid.to_excel(writer, sheet_name='Invalid', freeze_panes=(1,1))
    old.to_excel(writer, sheet_name='Old', freeze_panes=(1,1))
    failed_validation.to_excel(writer, sheet_name='Failed Validation', freeze_panes=(1,1))
    unresolved.to_excel(writer, sheet_name='Unresolved', freeze_panes=(1,1))
    valid_unresolved.to_excel(writer, sheet_name='Valid Unresolved', freeze_panes=(1,1))
    missing_speed.to_excel(writer, sheet_name='Missing Speed', freeze_panes=(1,1))
    non_operational.to_excel(writer, sheet_name='Non-operational', freeze_panes=(1,1))

report = pd.DataFrame(data=report_dicts).set_index('source')
report.to_excel('Report.xlsx')
print('Last updated ' + str(datetime.now()))

"""# Write detector locations to Excel file"""

df[df['locStatus'].str.contains('LOCATION_RESOLVED')][['latLongPointLoc|roadName|name','latLongPointLoc|roadName|prefix','latLongPointLoc|roadName|streetType','latLongPointLoc|roadName|suffix',
                                         'latLongPointLoc|coord|latitude','latLongPointLoc|coord|longitude']].to_excel('VDS-Locations.xlsx')